import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import List, Dict, Any


def load_env():
    env_path = Path(__file__).parent / '.env'
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

load_env()


class GitHubCommentPoster:
    def __init__(self, review_file: str):
        self.review_file = Path(review_file)

        if not self.review_file.exists():
            raise FileNotFoundError(f"File not found: {review_file}")

        self.metadata = None
        self.comments = []

    def parse_review_file(self) -> Dict[str, Any]:
        print(f"📖 Read the file: {self.review_file}")

        with open(self.review_file, 'r', encoding='utf-8') as f:
            content = f.read()

        metadata_match = re.search(
            r'<!-- REVIEW_METADATA\n(.*?)\n-->',
            content,
            re.DOTALL
        )

        if not metadata_match:
            raise ValueError("Metadata not found in the file. The file must be generated by the /review-pr.md.")

        metadata = json.loads(metadata_match.group(1))

        print(f"✅ Comments found: {len(metadata.get('comments', []))}")
        print(f"   PR: {metadata.get('owner')}/{metadata.get('repo')}#{metadata.get('pr_number')}")

        return metadata

    def preview_comments(self, metadata: Dict[str, Any]):
        comments = metadata.get('comments', [])

        if not comments:
            print("\n⚠️  No comments to publish.")
            return

        print("\n" + "="*60)
        print("📋 COMMENTS PREVIEW")
        print("="*60 + "\n")

        for i, comment in enumerate(comments, 1):
            severity_emoji = {
                'critical': '🔴 CRITICAL',
                'warning': '⚠️  WARNING',
                'suggestion': '💡 SUGGESTION'
            }.get(comment['severity'], '💬 COMMENT')

            print(f"{i}. {severity_emoji}")
            print(f"   File: {comment['path']}:{comment['line']}")
            print(f"   Text: {comment['body'][:100]}...")
            print()

    def confirm_posting(self) -> bool:
        print("="*60)
        response = input("Опубликовать эти комментарии на GitHub? (yes/no): ").strip().lower()
        return response in ['yes', 'y']

    def post_comments(self, metadata: Dict[str, Any]) -> bool:
        owner = metadata['owner']
        repo = metadata['repo']
        pr_number = metadata['pr_number']
        comments = metadata['comments']

        if not comments:
            print("✅  No comments to publish.")
            return True

        print(f"\n📤 Publishing {len(comments)} comments to GitHub...\n")

        github_token = os.getenv('GITHUB_TOKEN')

        review_comments = []
        for comment in comments:
            review_comments.append({
                "path": comment["path"],
                "line": comment["line"],
                "body": comment["body"]
            })

        review_data = {
            "body": "Code Review",
            "event": "COMMENT",  # или "REQUEST_CHANGES" / "APPROVE"
            "comments": review_comments
        }

        import tempfile
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as tmp:
            json.dump(review_data, tmp, ensure_ascii=False, indent=2)
            tmp_path = tmp.name

        try:
            cmd = [
                "gh", "api",
                f"repos/{owner}/{repo}/pulls/{pr_number}/reviews",
                "--method", "POST",
                "--input", tmp_path
            ]

            result = subprocess.run(cmd, capture_output=True, text=True, check=True)

            print("✅ Comments successfully published!")
            print(f"🔗 Просмотреть: https://github.com/{owner}/{repo}/pull/{pr_number}")

            return True

        except subprocess.CalledProcessError as e:
            print(f"\n❌ Ошибка при публикации комментариев:")
            print(f"   {e.stderr}")

            print("\n🔄 Пробую альтернативный метод (по одному комментарию)...")
            return self._post_comments_individually(owner, repo, pr_number, comments)

        finally:
            Path(tmp_path).unlink(missing_ok=True)

    def _post_comments_individually(self, owner: str, repo: str, pr_number: str, comments: List[Dict]) -> bool:
        success_count = 0
        fail_count = 0

        for i, comment in enumerate(comments, 1):
            print(f"  [{i}/{len(comments)}] Публикую комментарий к {comment['path']}:{comment['line']}...", end=" ")

            comment_text = f"**{comment['path']}:{comment['line']}**\n\n{comment['body']}"

            cmd = [
                "gh", "pr", "comment", pr_number,
                "--repo", f"{owner}/{repo}",
                "--body", comment_text
            ]

            try:
                subprocess.run(cmd, capture_output=True, text=True, check=True)
                print("✅")
                success_count += 1
            except subprocess.CalledProcessError as e:
                print(f"❌")
                fail_count += 1

        print(f"\n📊 Результат: {success_count} успешно, {fail_count} ошибок")
        return fail_count == 0

    def run(self, auto_confirm: bool = False):
        print(f"🚀 Запуск публикации комментариев\n")

        try:
            metadata = self.parse_review_file()
        except Exception as e:
            print(f"❌ Ошибка при чтении файла: {e}")
            return False

        self.preview_comments(metadata)

        if not auto_confirm and not self.confirm_posting():
            print("\n❌ Публикация отменена")
            return False

        success = self.post_comments(metadata)

        if success:
            print("\n" + "="*60)
            print("✅ ВСЕ КОММЕНТАРИИ ОПУБЛИКОВАНЫ!")
            print("="*60)
        else:
            print("\n⚠️  Некоторые комментарии не были опубликованы")

        return success


def main():
    parser = argparse.ArgumentParser(
        description="GitHub PR Comment Poster - публикует комментарии на GitHub"
    )
    parser.add_argument(
        "review_file",
        help="Путь к markdown файлу с ревью (созданному review_pr.py)"
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Автоматически подтвердить публикацию (пропустить запрос подтверждения)"
    )

    args = parser.parse_args()

    try:
        poster = GitHubCommentPoster(args.review_file)
        success = poster.run(auto_confirm=args.yes)
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n❌ Ошибка: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
